n = input('digite algo:')
print('o tipo primitivo desse valor é', type(n))
print('so tem espaço?', n.isspace())
print('é um numero?', n.isnumeric())
print('é alfabetico?', n.isalpha())
print('é alfanumerico?', n.isalnum())
print('esta em maiusculo?', n.isupper())
print('esta em minusculo?', n.islower())
print('esta capitalizado?', n.istitle())
